Add Chat PushNotification
Azure-Samples/communication-services-ios-quickstarts pull request #36
Opened 2022-07-27 21:58 UTC by angellan-msft

## Purpose

* Add the sample project "add-chat-push-notification" to guide Contoso user to enable push notification via chat SDK.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
* Test the code

Step 1: Create a Chat Thread with User A and User B. We will let User A receive push notifications from User B later. 
Step 2: Download this repo and finish all the prerequisites in QuickStart.
Step 3: Put User A’s <ACESS_TOEKN> and your <ACS_RESOURCE_ENDPOINT> into AppSettings.plist. 
Step 4: Set “Enable Bitcode” as “No” for two Pods targets – AzureCommunicationChat and Trouter. 
Step 5: Plug the IOS device into your mac, run the program and click “allow” when asked to authorize push notification on device. You should be able to see “Push Notification Started” printed on Console once the registration is successful. 
Step 6: Let User B sends a message to the thread created in step 1. You (User A) should be able to receive a push notification in your IOS device. 

## What to Check
Verify that the following are valid
N/A

## Other Information

2022-08-02 17:09 UTC, tjprescott requested changes

2022-08-02 17:10 UTC, tjprescott requested changes
Also, definitely add the Pods folder to gitignore which should scale down the file count significantly.

2022-08-02 21:52 UTC, angellan-msft commented on add-chat-push-notifications/SwiftPushTest/AppDelegate.swift
> +                chatClient.pushNotificationKeyHandler = appGroupPushNotificationKeyHandler
Comments fixed.

2022-08-02 21:53 UTC, angellan-msft commented on add-chat-push-notifications/SwiftPushTest/AppDelegate.swift
> +               In this sample app, we use the default AppGroupPushNotificationKeyHandler class provided by chat SDK to generate a key handler.
Comments updated to a more clear way.

2022-08-02 21:53 UTC, angellan-msft commented on add-chat-push-notifications/SwiftPushTest/AppDelegate.swift
> +            print("Notification settings: \(settings)")
Remove some useless print statements.

2022-08-02 21:54 UTC, angellan-msft commented
> Also, definitely add the Pods folder to gitignore which should scale down the file count significantly.

Pods folder removed.

2022-08-03 19:54 UTC, tjprescott approved these changes

2022-08-03 21:40 UTC, ddematheu2 approved these changes

2022-08-03 21:40 UTC, merged